### ISSUE TITLE
Error: command cmd.phpstan.scanFileForErrors not found

### ISSUE THREAD

**Issue by ljubadr** [SanderRonde/phpstan-vscode#3]
In the latest version `1.1.4` I'm getting error when I run `PHPStan: Scan current file for errors`. I've installed previous version `1.1.3` and it works without any issues

```
Command 'PHPStan: Scan current file for errors' resulted in an error (command 'cmd.phpstan.scanFileForErrors' not found)
```

In the output I found this error message

```
[2022-03-22 14:33:57.125] [exthost] [error] ReferenceError: let is not defined
	at /home/laradock/.vscode-server/extensions/sanderronde.phpstan-vscode-1.1.4/out/extension.js:72:18457
	at /home/laradock/.vscode-server/extensions/sanderronde.phpstan-vscode-1.1.4/out/extension.js:1:98
	at /home/laradock/.vscode-server/extensions/sanderronde.phpstan-vscode-1.1.4/out/extension.js:72:23270
	at /home/laradock/.vscode-server/extensions/sanderronde.phpstan-vscode-1.1.4/out/extension.js:1:98
	at Object.<anonymous> (/home/laradock/.vscode-server/extensions/sanderronde.phpstan-vscode-1.1.4/out/extension.js:73:1691)
	at Module._compile (internal/modules/cjs/loader.js:1063:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	at Module.load (internal/modules/cjs/loader.js:928:32)
	at Function.Module._load (internal/modules/cjs/loader.js:769:14)
	at Function.n._load (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
	at Function.S._load (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
	at Function.g._load (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
	at Module.require (internal/modules/cjs/loader.js:952:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/loader.js:5:101)
	at d._loadCommonJSModule (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:104:30307)
	at d._doActivateExtension (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:90:13385)
	at d._activateExtension (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:90:12327)
	at Object.actualActivateExtension (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:90:9470)
	at E._activateExtension (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:85:7777)
	at /home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:85:7459
	at Array.map (<anonymous>)
	at E._activateExtensions (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:85:7447)
	at E._activateExtensions (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:85:7512)
	at E.activateByEvent (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:85:4749)
	at d._activateByEvent (/home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:90:10408)
	at /home/laradock/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/workbench/api/node/extensionHostProcess.js:90:21713
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by SanderRonde** [comment]
Hmm strange, looks like something went wrong while bundling. I've uploaded a new version where this issue should be fixed.

**Comment by SanderRonde** [comment]
Closing this for now, let me see if you run into it again.

**Comment by ljubadr** [comment]
That was fast 😄 

I just tested the update and it works. Thanks for the fast response!

**Comment by SanderRonde** [comment]
Great!
